### ISSUE TITLE
Handle images in HelmChartConfig

### ISSUE THREAD

**Issue by Leobaillard** [nikhilsbhat/helm-images#25]
For my use case, I have a `HelmChartConfig` template that edits the default configuration for the Traefik instance in my clusters. It seems that helm-images is not able to get the images inside of that object type.

Here is an example:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
      additionalContainers:
        - name: nxlog
          image: {{ tpl .Values.log.images.nxlog . | replace "//" "/" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "PUID"
              value: "65532"
            - name: "GUID"
              value: "65532"
          volumeMounts:
            - name: fifo-logs
              mountPath: /logs
            - name: traefik-nxlog-config
              mountPath: /etc/nxlog/nxlog.conf
              subPath: nxlog.conf
```

In this case, the images in the `valuesContent` are not handled. Could this be added?

Thanks!
