### ISSUE TITLE
"image" in a configmap triggers output

### ISSUE THREAD

**Issue by lucacavazzana** [nikhilsbhat/helm-images#38]
# Bug description
It seems that occurrences of the word `image` in the configmap data trigger the parsing.

# How to reproduce

Given the following configmap in a test chart:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  test.yml: |
    foo_image_bar: SHOLD_NOT_PRINT_THIS
```

Get the list of images:

```
$ helm images get release ./test
SHOLD_NOT_PRINT_THIS
```

# Version
0.1.5

#
