### ISSUE TITLE
support crossplane provider packages

### ISSUE THREAD

**Issue by jkleinlercher** [nikhilsbhat/helm-images#45]
Kind: Provider
API-Group: pkg.crossplane.io
Attribute: .spec.package

Example:

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.39.0
```
