### ISSUE TITLE
Incorrect result when parsing the configmap.yaml

### ISSUE THREAD

**Issue by greyli-dell** [nikhilsbhat/helm-images#52]
Hi, thank you for the excellent project!

We found an image parsing issue when we added a new `configmap.yaml` file to the chart:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foo-upgrader.configmap". }}
data:
  charts: |
    {{- $charts := dict }}
    {{- $_ := set $charts "fooChart" (dict "release_name" "foo" "image" "fooImage") }}
    {{- $_ := set $charts "barChart" (dict "release_name" "bar" "image" "barImage") }}
    {{ toJson $charts | indent 4 }}
  update_repo: foo-updaterepo
```

Then the `helm images get` command returned the following result:

```
fooImage
barImage
```

IMO, these values should not be treated as images. Maybe we can filter out the image without a tag.
